# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build_and_deploy:

    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    branches:
      only: master

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:SmXDRvysrvJ6MAfuq/PqvZnBfmiuc5NyfffoRLH4ELk ndorfin+build-bot@gmail.com"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            npm i

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run build script
          command: |
            bash ./build.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy
          filters:
            branches:
              only: master
